# Templates for building a Quickstart guide in Markdown format.

[templates]
main = """
$prerequisites_section
$installation_section
$usage_section
$testing_section"""

prerequisites = """
Before you begin, ensure your system meets the following requirements:

$system_requirements
"""

installation = """
Install `$repo_name` using one of the following methods:

$install_steps
"""

usage = "$usage_instructions"

testing = "$test_instructions"

[install_steps]
template = """
1. Clone the $repo_name repository:

```sh
❯ git clone $repo_url
```

2. Navigate to the project directory:

```sh
❯ cd $repo_name
```

3. Install the project dependencies:

$install_commands
"""

[formatting]
system_requirements_prefix = "- **$key:** "
package_managers_label = "Package Manager"
containers_label = "Container Runtime"