# -- README-AI Mkdocs Configuration File ----------------------------------------

site_name: README-AI
site_description: "README-AI: Your AI-powered documentation assistant. Revolutionize your project documentation with automated, intelligent README generation."
site_author: Eli Salamie
site_url: https://docs.readme-ai.com/
repo_url: https://github.com/eli64s/readme-ai
repo_name: eli64s/readme-ai
edit_uri: edit/main/docs/
copyright: "© 2023 README-AI - Empowering developers with intelligent documentation"
site_dir: site/

theme:
  name: material
  custom_dir: docs/.overrides
  logo: assets/icons/readme-logo-purple.svg
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
    theme:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: black
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: eli64s
      repo: readme-ai
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eli64s/readme-ai
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/readmeai/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/zeroxeli/readme-ai

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

nav:
  - HOME:
      - index.md
      - Why README-AI?: why.md
      # - Philosophy: philosophy.md
      - Quick Start: quickstart/prerequisites.md
      - Troubleshooting: troubleshooting.md
      - Contributing: contributing.md
  - SETUP:
      - Prerequisites: quickstart/prerequisites.md
      - Installation: quickstart/installation.md
  - USAGE:
      - CLI: usage/cli.md
      - Docker: usage/docker.md
      - Streamlit: usage/streamlit.md
  - CONFIGURATION:
      - configuration/index.md
      - Badges: configuration/badges.md
      - Headers: configuration/header.md
      - Table of Contents: configuration/table_of_contents.md
      - Project Logo: configuration/project_logo.md
      - Emojis: configuration/emojis.md
  - INTEGRATIONS:
      - Models:
          - llms/index.md
          - OpenAI: llms/openai.md
          - Ollama: llms/ollama.md
          - Anthropic: llms/anthropic.md
          - Google Gemini: llms/google_gemini.md
      - Offline Mode: llms/offline_mode.md
  - EXAMPLES:
      - Gallery: examples/gallery.md
      # - Use Cases: examples/use-cases.md
  # - Advanced Topics:
  #     - Best Practices: advanced/best-practices.md
  #     - Custom Templates: advanced/custom-templates.md
  #     - Markdown Guide: advanced/markdown-guide.md
