# README-AI MkDocs Site Configuration

site_name: README-AI Docs
site_description: Explore readme-ai, a README file generator powered by large language model APIs.
site_url: https://docs.readme-ai.com/
site_author: readme-ai
repo_url: https://github.com/eli64s/readme-ai
repo_name: eli64s/readme-ai
remote_name: https://github.com/readme-ai/docs
docs_dir: "docs/docs/"

theme:
  name: material
  palette:
    primary: white
    accent: blueviolet
  language: en
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - header.autohide

nav:
  - Home: index.md
  - Quickstart:
      - "Requirements": quickstart/requirements.md
      - "Installation": quickstart/installation.md
      - Usage:
          - CLI: quickstart/usage/cli.md
          - Docker: quickstart/usage/docker.md
          - Streamlit: quickstart/usage/streamlit.md
  - Features:
      - "features/index.md"
      - Integrations:
          - "features/integrations/index.md"
          - OpenAI: features/integrations/openai.md
          - Ollama: features/integrations/ollama.md
          - Google Gemini: features/integrations/google-gemini.md
          - Offline Mode: features/integrations/offline-mode.md
  - Configuration:
      - configuration/index.md
      - "Basic": configuration/basic-examples.md
      - "Advanced": configuration/advanced-examples.md
      - Markdown Contents:
          - "Project Badges": configuration/content/project-badges.md
          - "Project Logo": configuration/content/project-logo.md
      - Markdown Templates:
          - "Header": configuration/templates/headers.md
          - "Table of Content": configuration/templates/table-of-contents.md
      - Examples:
          - "README Gallery": configuration/gallery.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.magiclink

extra_css:
  - css/custom.css
  - css/termynal.css

extra_javascript:
  - js/custom.js
  - js/termynal.js

plugins:
  - search
