# Readme-ai MkDocs Site Configuration

site_name: README-AI Docs
site_description: "README file generator, powered by large language model APIs 👾"
site_url: https://eli64s.github.io/readme-ai/
site_author: readme-ai
repo_url: https://github.com/eli64s/readme-ai
repo_name: eli64s/readme-ai
docs_dir: "docs/docs/"

theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    primary: white
    accent: blue
  language: en
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections

nav:
  - Home: index.md
  - Getting Started:
      - "System Requirements": prerequisites.md
      - "Installation": installation.md
      - "Usage": usage.md
      - "Configuration": configuration.md
  - Features:
      - "Overview": overview.md
      - "LLM Integrations": llm_integrations.md
  - Examples: examples.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra_css:
  - css/custom.css
  - css/termynal.css

extra_javascript:
  - js/custom.js
  - js/termynal.js

plugins:
  - search
